In [2]:
import numpy as np
import pandas as pd
from datetime import datetime, timedelta


import xarray as xr
import matplotlib.pyplot as plt
import sys
from scipy.ndimage import uniform_filter1d


In [ ]:
# # Python arrays
a = np.array([1, 0, 2, 3, 5, 7.])
N=6

S1 = np.arange(np.ceil(N/2), N)
S2 = np.ones(len(a)-N+1)*N
S3 = np.arange(N-1, np.floor(N/2), -1)
#S = [S1, S2, S3]
S = np.concatenate((S1, S2, S3)) 

y2 = uniform_filter1d(a, size=N, mode='constant') # for even window: backward avg. So window 2: x_m(i)=[x(i-1)+x(i)]/2
y2 = y2 * N / S
print(a)
print(y2)

In [ ]:
# Python lists
fruits = ["apple", "banana", "cherry"]
for i in range(2,3):
    fr = fruits[i]
    print(fr)
#for x in fruits:
#  print(x)

In [ ]:
# # Testing moving average

def moving_average_w_edges(x, N): # Note: still edge effects
    padded = np.pad(x, (N//2, N-1-N//2), mode='symmetric')   # for even window: backward avg. So window 2: x_m(i)=[x(i-1)+x(i)]/2
    padded = np.pad(x, (N//2, N-1-N//2), constant_values=0)   # for even window: backward avg. So window 2: x_m(i)=[x(i-1)+x(i)]/2

    print(padded)
    return np.convolve(padded, np.ones((N,))/N, mode='valid')

rng = np.random.default_rng()
a = rng.integers(9, size=(5))
a = np.array([1, 0, 2, 2, 5.])
#a_2d = rng.integers(6, size=(3,3))
a_float = a.astype(np.float64)

print(a)

y = moving_average_w_edges(a,3) # does not work for edges
# y = moving_average_w_edges(a_2d,2) # works not for 2D

print(y)

# Based on uniform filter. Gives same o utput as moving_avg_with_edges, when using mode=symmetric
y2 = uniform_filter1d(a_float, size=3, mode='constant') # for even window: backward avg. So window 2: x_m(i)=[x(i-1)+x(i)]/2
print(y2) # same output. So same result for edges

def running_mean(x, N):
    cumsum = np.cumsum(np.insert(x, 0, 0)) 
    return (cumsum[N:] - cumsum[:-N]) / float(N)

y3 = running_mean(a,3)
#print(y3)

In [ ]:
t1 = datetime(2023, 10, 13, 13, 0, 0)
t2 = datetime(2023, 10, 14, 13, 10, 0)
t = pd.date_range(t1,t2, freq='{}S'.format(1 / 16) )
print(t)

ds0_cropped = ds0.sel(t=slice(t0, t_end)) # crop dataset to the time range of interest

In [67]:
F_all = [8, 8, 16, 8, 16, 8] #[hz] sampling frequency

for i in range(6):
    if i != 3:
        print(i)
    elif F_all[i] == 8:
        print('apple')
    else:
        print('banana')

print(np.timedelta64())

0
1
2
apple
4
5
0 generic time units


In [63]:
a = np.array([1, 2, 3, 4, 5,6,7,8])
print(a)
b = a[::4]
print(b)


[1 2 3 4 5 6 7 8]
[1 5]


In [5]:
# Reshape XArray
x = xr.DataArray(np.arange(12).reshape(3, 4), dims=['x', 'y'])
print(x)

# Reshape XArray to 1d vector
x_1d = x.stack(z=('x', 'y'))
print(x_1d)

<xarray.DataArray (x: 3, y: 4)> Size: 96B
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
Dimensions without coordinates: x, y
<xarray.DataArray (z: 12)> Size: 96B
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
Coordinates:
  * z        (z) object 96B MultiIndex
  * x        (z) int64 96B 0 0 0 0 1 1 1 1 2 2 2 2
  * y        (z) int64 96B 0 1 2 3 0 1 2 3 0 1 2 3


In [15]:
# Coordinate transformation
xRD_all   = [np.nan,  72429.072,  72412.478,  72398.360,  72382.977,  72444.875]                          # x position of placement in field
yRD_all   = [np.nan, 452174.014, 452150.390, 452130.334, 452111.119, 452163.053]                          # y position of placement in field
xy_RD = np.array([xRD_all, yRD_all]).T
a = np.deg2rad(36)
transformation_matrix = np.array([ [np.cos(a), np.sin(a)],[-np.sin(a), np.cos(a)] ])
xy_loc = ( xy_RD - [71683.584, 452356.055] ) @ transformation_matrix
x_loc_all = xy_loc.T[0]
y_loc_all = xy_loc.T[1]

print(xy_RD)
print(transformation_matrix)
print(xy_loc)
print(x_loc_all)


[[       nan        nan]
 [ 72429.072 452174.014]
 [ 72412.478 452150.39 ]
 [ 72398.36  452130.334]
 [ 72382.977 452111.119]
 [ 72444.875 452163.053]]
[[ 0.80901699  0.58778525]
 [-0.58778525  0.80901699]]
[[         nan          nan]
 [710.11347622 290.91258949]
 [710.57448701 262.04666354]
 [710.9414061  237.52266651]
 [709.7905913  212.93550442]
 [729.34108593 291.33372455]]
[         nan 710.11347622 710.57448701 710.9414061  709.7905913
 729.34108593]
